# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: faysal <faysal@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/01/15 00:09:02 by faysal            #+#    #+#              #
#    Updated: 2021/01/15 00:35:48 by faysal           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libasm.a

SRCS = srcs/ft_strlen.s

SRCS_BONUS =

OBJS =

OBJS_BONUS =

ASM =

ASMFLAGS =

CC =

CFLAGS =

RM = rm -f

all		:	$(NAME)

$(NAME)	:	$(OBJS)
	ar rcs $(NAME) $(OBJS)